language: node_js
services:
- rabbitmq
node_js:
- '4.2'
dist: trusty
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
- bundle install
before_script:
- mosquitto -d
- npm install -g grunt-cli
script:
- npm test
- grunt jekyll:dist
after_deploy:
- grunt sitedeploy
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: MaBahjfJntupij63O69PyjK4TMgWox1/NRmLl1nM59fZlvLa0TKjxwUksIxvjghLZzJxbrvQyMY3F6aV6FSW5lLbANWVKND6gGniucMBw8xxamF1Dvzkb8KT/2vpEogFHJLycL1dDsGK11nAaYs39NTVSOYY6YBLrc+2OxiKZqo=
  on:
    tags: true
    repo: msgflo/msgflo
