language: node_js
services:
- rabbitmq
node_js:
- '4.2'
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
before_script:
- mosquitto -d
- npm install -g grunt-cli
script:
- npm test
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: mePf8GiNCSIZyOo8V1zGYzeQv4j7tzvgGvLyoPnutwDpmblEWI1ygtMRC7TP+yLp2GZ7eMhzaJvjQ0sEjeX7eV+xAOIQFMApUWLN4lihjIgnD5/jWnR1upkAldDlhaPVx+XIdZ7N5g6+W6EnlgRixlh3j0pao7yhW/+MKH2RLf0=
  on:
    tags: true
    repo: msgflo/msgflo
